name: Log latest release
on: push
jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query FindIssueID($owner:String!,$repo:String!,$issueNumber:Int!) {
              repository(owner:$owner,name:$repo) {
                issue(number:71) {
                  id
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: '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'
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
