name: Send Reward to the Assignee
on: push
jobs:
<<<<<<< HEAD
  logLatestRelease:
=======
  sendRewardToAssignee:
>>>>>>> main
    runs-on: ubuntu-latest
    steps:
      - name: Get Coins from Github Issue
        uses: octokit/graphql-action@v2.x
        id: get_coins
        with:
          query: |
            query GetCoinsAndAssigneeUser($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                issue(number: 71) {
                  assignees(first: 10) {
                    nodes {
                      id
                      avatarUrl
                      email
                      name
                      login
                    }
                  }
                  projectItems (first: 100) {
                    nodes {
                      fieldValueByName(name: "Reward") {
                        ... on ProjectV2ItemFieldNumberValue {
                          number
                        }
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest  release: ${{ steps.get_coins.outputs.data }}'"

      - name: Send Coins By Github Id
        uses: fjogeleit/http-request-action@v1
        id: send_coins
        with:
<<<<<<< HEAD
          url: 'https://reward-system-nextjs-wvfw.vercel.app/api/trpc/example.hello'
          method: 'GET'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"user": {"id": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].id }}", "login": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].login }}", "name": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].name }}", "email": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].email }}", "avatarUrl": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].avatarUrl }}"}, "coins": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.projectItems.nodes[0].fieldValueByName.number }}}}'
=======
          url: 'https://reward-system-nextjs-wvfw.vercel.app/api/trpc/example.hello,user.getByEmail?batch=1&input={%220%22:{%22json%22:{%22text%22:%22from%20tRPC%22}},%221%22:{%22json%22:{%22email%22:%22serudda.oficial@gmail.com%22}}}'
          method: 'GET'
          customHeaders: '{"Content-Type": "application/json"}'
>>>>>>> main
