name: Send Reward to the Assignee
on:
  pull_request:
    types: [closed]
jobs:
  send-reward-to-assignee:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Get Issue Number
        id: get_issue_number
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          issue_number=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'RS-[0-9]+' | head -1 | cut -d'-' -f2)
          echo "issue_number_int=$(echo $((issue_number)) | awk '{print int($0)}')" >> $GITHUB_OUTPUT

      - name: Get Coins from Github Issue
        uses: octokit/graphql-action@v2.x
        id: get_coins
        with:
          query: |
            query GetCoinsAndAssigneeUser($owner:String!, $repo:String!, $number:Int!) {
              repository(owner:$owner, name:$repo) {
                issue(number:$number) {
                  assignees(first: 10) {
                    nodes {
                      id
                      avatarUrl
                      email
                      name
                      login
                    }
                  }
                  projectItems (first: 100) {
                    nodes {
                      fieldValueByName(name: "Reward") {
                        ... on ProjectV2ItemFieldNumberValue {
                          number
                        }
                      }
                      project {
                        id
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          number: ${{steps.get_issue_number.outputs.issue_number_int}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Variables
        id: vars
        run: |
          echo "${{ steps.get_coins.outputs.data }}"
          echo "github_id=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].id }}" >> $GITHUB_OUTPUT
          echo "login=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].login }}" >> $GITHUB_OUTPUT
          echo "name=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].name }}" >> $GITHUB_OUTPUT
          echo "avatar_url=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].avatarUrl }}" >> $GITHUB_OUTPUT
          echo "email=${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].email }}" >> $GITHUB_OUTPUT
          echo "coins=400" >> $GITHUB_OUTPUT

      - name: Send Coins By Github Id
        uses: fjogeleit/http-request-action@v1
        id: send_coins
        with:
          url: 'https://reward-system-nextjs-wvfw-c5u2i07sw-serudda.vercel./api/trpc/user.sendCoinsByGithubId?batch=1'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"0":{"json":{"user":{"id":"${{ steps.vars.outputs.github_id }}","login":"${{ steps.vars.outputs.login }}","name":"${{ steps.vars.outputs.name }}","email":"${{ steps.vars.outputs.email }}","avatarUrl":"${{ steps.vars.outputs.github_id }}"},"coins":"${{ steps.vars.outputs.coins }}"}}}'
