name: Send Reward to the Assignee
on: push
jobs:
  sendRewardToAssignee:
    runs-on: ubuntu-latest
    steps:
      - name: Get Coins from Github Issue
        uses: octokit/graphql-action@v2.x
        id: get_coins
        with:
          query: |
            query GetCoinsAndAssigneeUser($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                issue(number: 71) {
                  assignees(first: 10) {
                    nodes {
                      id
                      avatarUrl
                      email
                      name
                      login
                    }
                  }
                  projectItems (first: 100) {
                    nodes {
                      fieldValueByName(name: "Reward") {
                        ... on ProjectV2ItemFieldNumberValue {
                          number
                        }
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Variables
        id: vars
        run: echo "githubId= ${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].id }}"

      - run: "echo '${{ steps.get_coins.outputs.data }}'"
      - run: "echo 'GithubId: ${{ steps.vars.outputs.githubId }} + ' - TEST''"
      - run: "echo 'Login: ${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].login }}'"
      - run: "echo 'Name: ${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].name }}'"
      - run: "echo 'AvatarUrl: ${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].avatarUrl }}'"
      - run: "echo 'Email: ${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].email }}'"

      - name: Send Coins By Github Id
        uses: fjogeleit/http-request-action@v1
        id: send_coins
        with:
          url: 'https://reward-system-nextjs-wvfw-6mv1tylh2-serudda.vercel.app/api/trpc/user.sendCoinsByGithubId?batch=1'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"0":{"json":{"user":{"id":"MDQ6VXNlcjEwMDc1NTMy","login":"serudda","name":"serudda","email":"serudda.oficial@gmail.com","avatarUrl":"https://avatars.githubusercontent.com/u/1016365?v=4"},"coins":1460}}}'
